### ISSUE TITLE
Question: Does it realy need to do sutherlandHodgman, Barycentric, InterpolateVertexes?

### ISSUE THREAD

**Issue by l1va** [fogleman/choppy#1]
https://github.com/fogleman/choppy/blob/a66928388e47bb0ad6a662e557e21987e2f5ec33/plane.go#L42

Michael, thank you for your open-source contributing! It helps.
Question - Could clipTriangle be something like next ? 
 Plane intersects triangle always by line, right? 

```
if len(inFront) == 3 {
	triangles = append(triangles, t)
} else if len(inFront) == 2 {
	line := plane.IntersectTriangle(&t)
	triangles = append(triangles, NewTriangle(inFront[0], line.P1, line.P2))
	triangles = append(triangles, NewTriangle(inFront[0], line.P2, inFront[1]))
} else if len(inFront) == 1 {
	line := plane.IntersectTriangle(&t)
	triangles = append(triangles, NewTriangle(inFront[0], line.P1, line.P2))
}
```

As i understand you use just more common way with sutherlandHodgman, Barycentric, etc, right? 
Where plane.IntersectTriangle(&t) can be like this:
```
func (p Plane) IntersectTriangle(t *Triangle) *Line {
	v1 := p.IntersectSegment(t.P1, t.P2)
	v2 := p.IntersectSegment(t.P2, t.P3)
	v3 := p.IntersectSegment(t.P3, t.P1)
	var p1, p2 Point
        ...........
	n := p1.VectorTo(p2).Cross(p.N)
	..........
	return &Line{p2, p1}
}
```

**Comment by fogleman** [comment]
You might be right. Have you tried it? :)

**Comment by l1va** [comment]
Yes, i tried, but i had problems with torn edges. 
But today i found that i have a mistake: 
```
triangles = append(triangles, NewTriangle(inFront[0], line.P1, line.P2))
triangles = append(triangles, NewTriangle(inFront[0], line.P2, inFront[1]))
```
Here i create two triangles from quadrangle but i can't just use line.P1 and line.P2 in that order. 
Because it can be inFront[0] -> line.P1 -> line.P2 -> inFront[1]  quadrangle, but can be inFront[0] -> line.P2 -> line.P1 -> inFront[1] ( in traversal order ).

And now - yes, it works.

And here as i understand you use again p.intersectTriangle(t) for plane surface
https://github.com/fogleman/choppy/blob/a66928388e47bb0ad6a662e557e21987e2f5ec33/plane.go#L48-L67
